{% set name = "py-applescript" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/rdhyee/py-applescript/archive/{{ version }}.tar.gz"
  sha256: 22edcf44806e6da0d31fba48dd8b504c7d4aed3695b54b058177d7c97b072369

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [not osx]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyobjc-framework-cocoa

test:
  imports:
    - applescript

about:
  home: https://github.com/rdhyee/py-applescript
  license:  CC0-1.0
  license_family: Public-Domain
  license_file: LICENSE
  summary: "An easy-to-use Python wrapper for NSAppleScript, allowing Python scripts to communicate with AppleScripts and AppleScriptable applications."
  doc_url: https://pypi.org/project/py-applescript
  dev_url: https://github.com/rdhyee/py-applescript

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
